export const RESERVED_USERNAMES = new Set([
  "admin",
  "administrator",
  "ceo",
  "employee",
  "staff",
  "api",
  "b",
  "g",
  "r",
  "bio",
  "bios",
  "biopage",
  "activelinks",
  "analytics",
  "expire",
  "expired",
  "login",
  "join",
  "signin",
  "signup",
  "register",
  "auth",
  "dashboard",
  "settings",
  "help",
  "support",
  "about",
  "terms",
  "privacy",
  "root",
  "system",
  "official",
  "relaylink",
  "relay",
  "u",
  "pro",
  "billing",
  "pricing",
  "upgrade",
  "checkout",
  "domainyourlink",
  "null",
  "undefined",
]);

export function isReservedUsername(username: string): boolean {
  const clean = username.trim().toLowerCase();
  return RESERVED_USERNAMES.has(clean);
}
